kind: pipeline
name: default
workspace:
    base: /go
    path: src/github.com/fanux/sealos

# go mod vender
#environment:
#    GO111MODULE: on

steps:
- name: build
  image: golang:1.12
  commands:
      - go build -o sealos -ldflags "-X github.com/fanux/sealos/version.Version=${DRONE_TAG=latest}" main.go

- name: publish-oss
  image: fanux/ossutil
  environment:
    OSS_CONFIG:
      from_secret: oss-config
  commands:
    - echo $OSS_CONFIG |base64 --decode >> ~/.ossutilconfig
    - ossutil64 cp sealos oss://sealyun/${DRONE_TAG=latest}/sealos
    - echo "[oss 下载地址](https://sealyun.oss-cn-beijing.aliyuncs.com/${DRONE_TAG=latest}/sealos)" >> Note.md
  when:
    event:
      - tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
        from_secret: git-release-token
    files: sealos
    title: ${DRONE_TAG}
    note: Note.md
  when:
     event:
     - tag

# 42 is the build number 
# drone build promote fanux/sealos 42 test
- name: e2etest
  image: golang:1.12
  commands:
    - echo "this is sealos test"
  when:
    event:
    - promote
    target:
    - test
