kind: pipeline
name: default
workspace:
    base: /go
    path: src/github.com/fanux/sealos

# go mod vender
#environment:
#    GO111MODULE: on

steps:
- name: build
  image: golang:1.12
  commands:
      - go build -o sealos -ldflags "-X main.Version=${DRONE_TAG=latest}" cmd/version.go

- name: publish
  image: plugins/github-release
  settings:
    api_key:
        from_secret: git-release-token
    files: sealos
    title: ${DRONE_TAG}
    note: Note.md
  when:
     event:
     - tag
