---
- hosts: k8s-master
  roles:
  - { role: etcd, when: order is defined }
  - { role: kube-master, when: order is defined }

#- hosts: slb
#  roles:
#  - { role: haproxy }
#  - { role: keepalived }
#
#- hosts: k8s-node
#  roles:
#    - [role: node]
