---
- name: start a temp kubelet to init etcd
  shell: echo "pass"

- name: make etcd crts
  shell: mkdir -p /etc/kubernetes/pki/cfssl
  shell: mkdir -p /etc/kubernetes/manifests

- name: copy etcd.service 
  template: src=/etc/ansible/roles/etcd/templates/etcd.service.j2  dest=/etc/kubernets/manifests/etcd.yaml mode=777
